Implement a console program to calculate triangle area.
KaplenkoAnastasiia/python_course pull request #2
Opened 2021-09-16 21:07 UTC by KaplenkoAnastasiia

2021-09-17 09:35 UTC, ahodkov requested changes

2021-09-17 09:35 UTC, ahodkov commented on tasks/task02/task02.py
> +        print("\n Menu:", "1. Calculate triangle area by base and height",
I think it should be in a variable

2021-09-17 09:35 UTC, ahodkov commented on tasks/task02/task02.py
> +def calculate_area_by_height(userString):
`user_string`

2021-09-17 09:35 UTC, ahodkov commented on tasks/task02/task02.py
> +    if values.__len__() != 2:
`len(values)`

2021-09-17 09:35 UTC, ahodkov commented on tasks/task02/task02.py
> +    base, height = values
Need positive number(or no-zero) checks

2021-09-17 09:35 UTC, ahodkov commented on tasks/task02/task02.py
> +    if values.__len__() != 3:
same

2021-09-17 09:35 UTC, ahodkov commented on tasks/task02/task02.py
> +    side1, side2, angle = values
same

2021-09-17 09:35 UTC, ahodkov commented on tasks/task02/task02.py
> +def calculate_area_by_angle(userString):
same

2021-09-17 09:35 UTC, ahodkov commented on tasks/task02/task02.py
> +    while True:
Better to use `user_input != 3`

2021-09-19 20:20 UTC, KaplenkoAnastasiia commented on tasks/task02/task02.py
> +    base, height = values
added

2021-09-21 07:59 UTC, ahodkov approved these changes

2021-09-21 09:02 UTC, merged